---
# tasks file to disable swap

- name: "Disable swap on hosts"
  command: swapoff -a

- name: "Disable SWAP in fstab"
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'