---
# tasks file for kubernetes-workers-join

########################################################################## INIT
- name: "Reset kubeadm if present"
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: "Remove old ca.crt"
  file:
    path: /etc/kubernetes
    state: absent
    force: yes

- name: "Create Kubernetes ETCD folders"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: root
    group: root
    mode: '0640'


#################################################################### COPY CERTS
- name: "Copy Kubernetes Master PKI files"
  copy: 
    src: "/tmp/{{ kubernetes_first_master_hostname }}/pki"
    dest: /etc/kubernetes/
    owner: root
    group: root


############################################################## GET JOIN COMMAND
- name: "Generate join token"
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ kubernetes_first_master_hostname }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"


################################################################## JOIN CLUSTER
- name: "Join Master replicas to cluster"
  shell: "{{ kubeadm_join }} --ignore-preflight-errors=all"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


