---
# tasks file for user-ssh-copy-id

- name: "Display"
  debug:
    msg: "lookup('file', /home/{{ user_user }}/.ssh/{{ user_ssh_key }})"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/ansible/.ssh/id_ed25519.pub
    dest: /home/ansible/id_ed25519.pub
    owner: ansible
    group: ansible
    mode: '0644'

#- name: Set authorized key taken from file
#  authorized_key:
#    exclusive: yes
#    manage_dir: yes
#    user: ansible
#    state: present
#    key: "{{ lookup('file', '/home/ansible/id_ed25519.pub') }}"


#- name: "Set authorized key in alternate location"
#  ansible.posix.authorized_key:
#    key: "/home/ansible/.ssh/id_ed25519.pub"
#    exclusive: yes
#    manage_dir: yes
#    user: ansible
#    state: present
#    path: "/home/ansible/.ssh/authorized_keys"

