---
# tasks file for kubernetes-masters-setup

########################################################################## INIT
- name: "Reset kubeadm if present"
  shell: kubeadm reset -f
  register: kubeadm_reset
  when: inventory_hostname != kubernetes_first_master_hostname

- name: "Remove old ca.crt"
  file:
    path: /etc/kubernetes/pki/ca.crt
    state: absent
  when: inventory_hostname != kubernetes_first_master_hostname

- name: "Create Kubernetes ETCD folders"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: root
    group: root
    mode: '0640'
  when: inventory_hostname != kubernetes_first_master_hostname


#################################################################### COPY CERTS
- name: "Copy Kubernetes Master PKI files"
  copy: 
    src: "/tmp/{{ kubernetes_first_master_hostname }}/pki"
    dest: /etc/kubernetes/
    owner: root
    group: root
  when: inventory_hostname != kubernetes_first_master_hostname


############################################################## GET JOIN COMMAND
- name: "Generate join token"
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ kubernetes_first_master_hostname }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }} --control-plane --ignore-preflight-errors=all"
  when: inventory_hostname != kubernetes_first_master_hostname


################################################################## JOIN CLUSTER
- name: "Join Master replicas to cluster"
  shell: "{{ kubeadm_join }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: inventory_hostname != kubernetes_first_master_hostname


