---
# Remove ETCD installation

- name: "Disable ETCD service"
  ansible.builtin.systemd:
    name: etcd
    state: stopped
    enabled: no

- name: "Reset kubeadm if present"
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: "Remove ETCD service directory"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/lib/systemd/system/etcd.service"
    - "/var/lib/etcd"
    - "/etc/default/etcd"
    - "/etc/kubernetes"


- name: "Remove ETCD packages"
  package:
    name: [ 'etcd', 'kubelet', 'kubeadm', 'kubernetes-cni' ]
    state: absent
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes
    update_cache: true


