---
# Deploy Prometheus 

- name: "Deploy Prometheus"
  hosts: prometheus-server
  vars:
    prometheus_url: https://github.com/prometheus/prometheus/releases/download/v2.33.3/prometheus-2.33.3.linux-amd64.tar.gz
  become: yes
  gather_facts: true
  roles:
    - role: "prometheus/prometheus-install"

- name: "Deploy Prometheus Node Exporter"
  hosts: [admin-server,cluster,nfs_servers]
  become: yes
  gather_facts: true
  vars:
    node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz 
  roles:
    - role: "prometheus/prometheus-node-exporter"

